spring:
    data:
      mongodb:
        uri:  mongodb://AdminTask:admin@clustertask-shard-00-00-1f2s8.mongodb.net:27017,clustertask-shard-00-01-1f2s8.mongodb.net:27017,clustertask-shard-00-02-1f2s8.mongodb.net:27017/test?ssl=true&replicaSet=ClusterTask-shard-0&authSource=admin&retryWrites=true&w=majority






